/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_fmo_Lib */

#ifndef _Included_cz_fmo_Lib
#define _Included_cz_fmo_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_fmo_Lib
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_fmo_Lib_getHelloString
  (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    recordingStart
 * Signature: (IILcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_recordingStart
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    recordingFrame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_recordingFrame
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cz_fmo_Lib
 * Method:    recordingStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_recordingStop
  (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    benchmarkingStart
 * Signature: (Lcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_benchmarkingStart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    benchmarkingStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_benchmarkingStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cz_fmo_Lib_Callback */

#ifndef _Included_cz_fmo_Lib_Callback
#define _Included_cz_fmo_Lib_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
