/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_fmo_Lib */

#ifndef _Included_cz_fmo_Lib
#define _Included_cz_fmo_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_fmo_Lib
 * Method:    detectionStart
 * Signature: (IILcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_detectionStart
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    detectionFrame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_detectionFrame
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cz_fmo_Lib
 * Method:    detectionStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_detectionStop
  (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    benchmarkingStart
 * Signature: (Lcz/fmo/Lib/Callback;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_benchmarkingStart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cz_fmo_Lib
 * Method:    benchmarkingStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_benchmarkingStop
  (JNIEnv *, jclass);

/*
 * Class:     cz_fmo_Lib
 * Method:    generateCurve
 * Signature: (Lcz/fmo/Lib/Detection;[FLcz/fmo/graphics/TriangleStripRenderer/Buffers;)V
 */
JNIEXPORT void JNICALL Java_cz_fmo_Lib_generateCurve
  (JNIEnv *, jclass, jobject, jfloatArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cz_fmo_Lib_Detection */

#ifndef _Included_cz_fmo_Lib_Detection
#define _Included_cz_fmo_Lib_Detection
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class cz_fmo_Lib_Callback */

#ifndef _Included_cz_fmo_Lib_Callback
#define _Included_cz_fmo_Lib_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
